// Generated by gencpp from file time_sync_pkg/SyncData.msg
// DO NOT EDIT!


#ifndef TIME_SYNC_PKG_MESSAGE_SYNCDATA_H
#define TIME_SYNC_PKG_MESSAGE_SYNCDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/LaserScan.h>

namespace time_sync_pkg
{
template <class ContainerAllocator>
struct SyncData_
{
  typedef SyncData_<ContainerAllocator> Type;

  SyncData_()
    : image()
    , scan()  {
    }
  SyncData_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , scan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan_type;
  _scan_type scan;





  typedef boost::shared_ptr< ::time_sync_pkg::SyncData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::time_sync_pkg::SyncData_<ContainerAllocator> const> ConstPtr;

}; // struct SyncData_

typedef ::time_sync_pkg::SyncData_<std::allocator<void> > SyncData;

typedef boost::shared_ptr< ::time_sync_pkg::SyncData > SyncDataPtr;
typedef boost::shared_ptr< ::time_sync_pkg::SyncData const> SyncDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::time_sync_pkg::SyncData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::time_sync_pkg::SyncData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::time_sync_pkg::SyncData_<ContainerAllocator1> & lhs, const ::time_sync_pkg::SyncData_<ContainerAllocator2> & rhs)
{
  return lhs.image == rhs.image &&
    lhs.scan == rhs.scan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::time_sync_pkg::SyncData_<ContainerAllocator1> & lhs, const ::time_sync_pkg::SyncData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace time_sync_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::time_sync_pkg::SyncData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::time_sync_pkg::SyncData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::time_sync_pkg::SyncData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::time_sync_pkg::SyncData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::time_sync_pkg::SyncData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::time_sync_pkg::SyncData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::time_sync_pkg::SyncData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "149818d6ea321fa3e69c3870cecbc7b3";
  }

  static const char* value(const ::time_sync_pkg::SyncData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x149818d6ea321fa3ULL;
  static const uint64_t static_value2 = 0xe69c3870cecbc7b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::time_sync_pkg::SyncData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time_sync_pkg/SyncData";
  }

  static const char* value(const ::time_sync_pkg::SyncData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::time_sync_pkg::SyncData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n"
"sensor_msgs/LaserScan scan\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
;
  }

  static const char* value(const ::time_sync_pkg::SyncData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::time_sync_pkg::SyncData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.scan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::time_sync_pkg::SyncData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::time_sync_pkg::SyncData_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "scan: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIME_SYNC_PKG_MESSAGE_SYNCDATA_H
